source 'https://rubygems.org'
ruby '2.2.2'
gem 'oj'
gem 'mongo', '~>2.0.6'
gem 'grape', '~>0.13.0'
gem 'rack-cors'
gem 'shotgun'
gem 'grape-entity'
gem 'typhoeus'
gem 'puma'
gem 'sinatra'
gem 'activesupport'
gem 'jwt'
gem 'grape_logging'
gem 'parallel'
gem 'grape-swagger'
gem 'algoliasearch'
gem 'nokogiri'
gem 'newrelic_rpm'
gem 'thor'
gem 'skylight', '~>0.8.0'

group :development do
  gem 'guard'
  gem 'guard-shotgun'
  gem 'foreman'
  gem 'pry'
end
