source 'https://rubygems.org'
ruby '2.2.6'
gem 'oj', '~> 3.6.5'
gem "actionview", ">= 4.2.11.1"
gem 'mongo', '~>2.0.6'
gem 'bson'
gem 'bson_ext'
gem 'grape', '~>0.13.0'
gem 'rack-cors'
gem 'shotgun'
gem 'grape-entity'
gem 'typhoeus'
gem 'puma', '~>2.11.3'
gem 'sinatra'
gem 'activesupport'
gem 'jwt'
gem 'grape_logging'
gem 'parallel'
gem 'grape-swagger', '~>0.10.2'
gem 'algoliasearch', '~>1.7.0'
gem 'nokogiri', '~>1.6.8'
gem 'newrelic_rpm'
gem 'thor'
gem 'skylight', '~>0.10.6'
gem "slack-notify"
gem 'virtus'
gem 'dry-validation'
gem 'asana'
gem 'postmark'
gem 'dotenv'
gem 'jemalloc'

group :development do
  gem 'guard'
  gem 'guard-shotgun'
  gem 'foreman'
  gem 'pry'
  gem 'rspec'
  gem 'rack-test'
end
