#!/usr/bin/env ruby

require 'thor'
require 'fileutils'
require 'mongo'
require_relative 'importer'

class ImporterCLI < Thor


  desc "setup", "Set up dev environment script"
  def setup

    # Add the .env file
    if File.exists?('.env') == false
      FileUtils.copy('sample.env', '.env')
    end

    # create the sample user
    user = $db[:users].find({"apiKey" => "vZKoJwFB1PTJnozKBSANADc3"}).to_a.first
    if user.nil?
      $db[:users].insert_one({
        _id:     SecureRandom.uuid().to_s.upcase.gsub('-', ''),
        apiKey:  "vZKoJwFB1PTJnozKBSANADc3",
        profile: {}
      })
    end
  end


  desc "import", "Import standards from ASN"
  option :download,          :type => :boolean, :default => true
  option :algolia,         :type => :boolean, :default => false
  option :all,             :type => :boolean, :default => false
  option :cache_standards, :type => :boolean, :default => true
  def import
    Importer.run({
      import_all:      options[:all],
      send_to_algolia: options[:algolia],
      cache_standards: options[:cache_standards],
      download_standards: options[:download]
    })
  end

  desc "cache", "Cache standards"
  def cache
    CachedStandards.all
  end

  desc "algolia", "Send to  standards"
  def algolia
    SendToAlgolia.all_standard_sets
  end


end

ImporterCLI.start(ARGV)
