language: ruby

sudo: false

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.4.2
  - 2.3.5

matrix:
  fast_finish: true

  include:
    - rvm: 2.2.8
      env:
    - rvm: ruby-head
      env:
    - rvm: jruby-head
      env:
    - rvm: rbx-2
      env:

  allow_failures:
    - rvm: 2.2.8
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
