language: ruby

sudo: false

before_install:
  - gem update --system
  - gem install bundler

after_success:
  - bundle exec danger

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0

env:
  - GRAPE_ENTITY=0.6.1
  - GRAPE_ENTITY=0.7.1

matrix:
  fast_finish: true

  include:
    - rvm: 2.3.8
      env:
    - rvm: ruby-head
      env:
    - rvm: jruby-head
      env:
    - rvm: rbx-2
      env:

  allow_failures:
    - rvm: 2.3.8
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
